docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Reference:
        - AutoloaderFactory: autoloader-factory.md
        - StandardAutoloader: standard-autoloader.md
        - ClassMapAutoloader: class-map-autoloader.md
        - ModuleAutoloader: module-autoloader.md
        - SplAutoloader: spl-autoloader.md
        - PluginClassLoader: plugin-class-loader.md
        - ShortNameLocator: short-name-locator.md
        - PluginClassLocator: plugin-class-locator.md
        - "ClassMap Generator": classmap-generator.md
site_name: laminas-loader
site_description: laminas-loader
repo_url: 'https://github.com/laminas/laminas-loader'
